################################################################
# Configuration section
################################################################

CPPFLAGS := -I. $(shell root-config --cflags)
CXXFLAGS := -O3 -g
LDFLAGS  := $(shell root-config --libs)

################################################################
# Dependency generation
################################################################

DEPEND_TGTS = -MQ '$(patsubst %.d,%.o,$@)'

# Always use gcc as icc used to have trouble with this (? check if still true)
MAKEDEPEND = gcc -MM -MG ${DEPEND_TGTS} ${CPPFLAGS}

%.d: %.cc
	${MAKEDEPEND} -o $@ $<
