// modified autogenerated tree->MakeClass()

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TString.h>

class PlotValidation {
public :
  TFile          *file;
  TTree          *fChain;   //!pointer to the analyzed TTree or TChain
  Int_t           fCurrent; //!current Tree number in a TChain

  // Declaration of leaf types
  Int_t           evtID;
  Int_t           trackID;
  Int_t           layer;
  Float_t         x_mc;
  Float_t         vx_mc;
  Float_t         x_up;
  Float_t         vx_up;
  Float_t         x_hit;
  Float_t         exx_up;
  Float_t         evxvx_up;
  Float_t         exvx_up;
  Float_t         evxx_up;
  Float_t         exx_hit;
  Float_t         chi2;

  // List of branches
  TBranch        *b_evtID;   //!
  TBranch        *b_trackID;   //!
  TBranch        *b_layer;   //!
  TBranch        *b_x_mc;   //!
  TBranch        *b_vx_mc;   //!
  TBranch        *b_x_up;   //!
  TBranch        *b_vx_up;   //!
  TBranch        *b_x_hit;   //!
  TBranch        *b_exx_up;   //!
  TBranch        *b_evxvx_up;   //!
  TBranch        *b_exvx_up;   //!
  TBranch        *b_evxx_up;   //!
  TBranch        *b_exx_hit;   //!
  TBranch        *b_chi2;   //!

  PlotValidation(TString filename);
  ~PlotValidation();
  Int_t    GetEntry(Long64_t entry);
  Long64_t LoadTree(Long64_t entry);
  void     Init(TTree *tree);
  void     Validation();
};
